### ISSUE TITLE
Improve installer

### ISSUE THREAD

**Issue by curtisdelicata** [liberu-genealogy/genealogy-old#100]
Improve installer. Does it handle Neo4j?

**Comment by zhzmst** [comment]
怎样改变？

**Comment by curtisdelicata** [comment]
The web installer has been removed for now.
The docker install method has been successfully tested.
Standard installation with Travis successfully builds.
Windows not tested.

**Comment by curtisdelicata** [comment]
We were using https://github.com/RachidLaasri/LaravelInstaller

Need to discuss whether to have a web installer and what is required.

Any pull requests are welcome to be considered.
