### ISSUE TITLE
File missing vendor/autoload.php

### ISSUE THREAD

**Issue by PrajaktaSoftware** [liberu-genealogy/genealogy-old#1168]
Dear Sir/Madam

Downloaded the code
to test

`require __DIR__.'/../vendor/autoload.php';`

the file"autoload.php" was missing

This is  a **bug | feature request**.

### Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

**Comment by curtisdelicata** [comment]
Have you run composer install?

**Comment by PrajaktaSoftware** [comment]
NO sir
but pls guide me how to install.. 
I am using EASYPHP DEVSERVER 17 php 7.0
thanks in advance

**Comment by curtisdelicata** [comment]
There is a guide in the README file how to install. Have you downloaded from git or a release? PHP 7.4 is required for latest version.
