### ISSUE TITLE
Can't install under windows as it requires Horizon

### ISSUE THREAD

**Issue by activemonkeys** [liberu-genealogy/genealogy-old#15]
Thanks for starting this nice project. Unable to install under windows as it requires Horizon.

**Comment by curtisdelicata** [comment]
Hello,

Thank you for letting me know.

Try adding --ignore-platform-reqs to the composer install command.

**Comment by activemonkeys** [comment]
Thanks - although Horizon is still referred to in the AuthServiceProvider, adding --ignore-platform-reqs made me install your code under windows. 

https://github.com/laravel-genealogy/genealogy/blob/master/app/Providers/AuthServiceProvider.php

**Comment by curtisdelicata** [comment]
Do you get any errors?

I have a Windows system available but I use Vagrant so it's under Ubuntu. Have not tested on XAMPP or similar.


________________________________

**Comment by activemonkeys** [comment]
Currently no errors. Using Laragon under windows: https://laragon.org/ As you seem to update your code frequently, I"ll test every now and then with a new vanilla installation and will let you know.

**Comment by curtisdelicata** [comment]
Thank you.

________________________________
