### ISSUE TITLE
 vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php:84

### ISSUE THREAD

**Issue by alvarogallo** [liberu-genealogy/genealogy-old#1504]
This is  a **bug | feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(genealogy is made of many specialized packages: https://github.com/modularsoftware)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

**Comment by fstoll3** [comment]
I get this error "Auth guard [auth] is not defined." and I have no idea how to fix it. Any suggestions?

**Comment by curtisdelicata** [comment]
We will look into this.

**Comment by curtisdelicata** [comment]
Please see familytree365/backend and familytree365/frontend we abandoned the Laravel Enso version.

**Comment by curtisdelicata** [comment]
We are now back to working with Enso. We plan to adapt Nuxt and all our changes and improvements done to the alternative created.

**Comment by curtisdelicata** [comment]
Fixed.
