### ISSUE TITLE
Fix Laravel Gedcom import and export

### ISSUE THREAD

**Issue by curtisdelicata** [liberu-genealogy/genealogy-old#1588]
This is  a **bug | feature request**.

### Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

**Comment by curtisdelicata** [comment]
laravel-gedcom:

improve import code by refactoring taking into account we want PHP 8 and latest PSR standards
finish export to include all data
add seeders for optional fake dummy data

php-gedcom:
same as above regarding PHP  8 and PSR - refactor
fix PSR4 loading etc

**Comment by heru0502** [comment]
> laravel-gedcom:
> 
> improve import code by refactoring taking into account we want PHP 8 and latest PSR standards
> finish export to include all data
> add seeders for optional fake dummy data
> 
> php-gedcom:
> same as above regarding PHP 8 and PSR - refactor
> fix PSR4 loading etc

OK
