### ISSUE TITLE
WikiTree API

### ISSUE THREAD

**Issue by curtisdelicata** [liberu-genealogy/genealogy-old#1590]
This is  a **bug | feature request**.

### Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

**Comment by curtisdelicata** [comment]
Copied across, needs refactoring to Enso layout and improving features.

**Comment by prihutomo** [comment]
feature can be tested but requires access to wikitree

can you help me about it?

Here I attach the test results
![Screenshot 2021-08-24 at 23 30 44](https://user-images.githubusercontent.com/43591658/130645788-c9d546aa-dbfb-4267-92ce-528edd77b5ef.png)

**Comment by curtisdelicata** [comment]
Register a test account.
