### ISSUE TITLE
Invite users to view tree with options to not show living persons

### ISSUE THREAD

**Issue by curtisdelicata** [liberu-genealogy/genealogy-old#1594]
This is  a **bug | feature request**.

### Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

**Comment by curtisdelicata** [comment]
Invite members to see your tree with different varying permissions of what they can see. For example, living or not individuals. We also need to calculate estimated living if no birth year or if no death date but displayed as living

**Comment by curtisdelicata** [comment]
Table builder to restrict data based on age of people on peopletable, forms to be restricted to only work if using your own tree (if tenancy id company owner not == auth id)

**Comment by robertnicjoo** [comment]
TODO:

- [x] double check: person name on invite form
- comes from register form and gets user email by default unless there is cache issue with browser then it will be null
- [x] double check: family list on selected company from dashboard
- works fine
- [x] double check: don't allow own the company they are not allow to edit/delete/ etc.
- added
