### ISSUE TITLE
Make a tree public and restrict living records. Optional for users

### ISSUE THREAD

**Issue by curtisdelicata** [liberu-genealogy/genealogy-old#1595]
This is  a **bug | feature request**.

### Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

**Comment by curtisdelicata** [comment]
Algolia from enso maybe useful with vue instant search for frontend.

**Comment by curtisdelicata** [comment]
To be discussed but Algolia or Meliasearch should work well. We need to index public records.

**Comment by curtisdelicata** [comment]
Public by default. User can make their tree private.

**Comment by curtisdelicata** [comment]
Improve the template of companies creation. app / form / builders / Company and app / form / templates company.json copied from vendor

**Comment by curtisdelicata** [comment]
Template improved. Using enum temporary for private and public, needs to be stored in database so the indexing script can check.

**Comment by robertnicjoo** [comment]
Done.
