### ISSUE TITLE
Add baptism to geneanum api

### ISSUE THREAD

**Issue by curtisdelicata** [liberu-genealogy/genealogy-old#1697]
This is  a **bug | feature request**.

### Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/familytree365)
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

**Comment by prihutomo** [comment]
the following is my work (commit - https://github.com/familytree365/genealogy/commit/5e5626d6bea5bd24579649282eb0f8761a9bfb27)
