### ISSUE TITLE
Fix phpunit tests for build

### ISSUE THREAD

**Issue by curtisdelicata** [liberu-genealogy/genealogy-old#1729]
This is  a **bug | feature request**.

### Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/familytree365)
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

**Comment by devpro9219** [comment]
Hi Curtis. Can you please give me the answer quickly?
