### ISSUE TITLE
[typo] Error link in readme

### ISSUE THREAD

**Issue by David-Maran** [liberu-genealogy/genealogy-old#1788]
The link in readme demo section:

```html
https://www.familytree365.com-
````
will be
```html
https://www.familytree365.com
````

I thought the site was closed .... 
And
Creating an account to try the demo is a repellant (that's just my opinion)

**Comment by curtisdelicata** [comment]
Thank you for your report. The reason the demo is registrations is to show how the code works but we may create a demo account to use.
