### ISSUE TITLE
Exception while migrate

### ISSUE THREAD

**Issue by atmohsin** [liberu-genealogy/genealogy-old#18]
Hi,

Getting below exception while

php artisan -v migrate

 Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `created_at` timestamp null, `updated_at` timestamp null) default' at line 1 (SQL: create table `preferences` (`id` int unsigned not null auto_increment primary key, `user_id` int unsigned not null, `value` json not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

 1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `created_at` timestamp null, `updated_at` timestamp null) default' at line 1")
      /Users/apple/Documents/work/dev/laraveldev/genealogy/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:82

  2   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `created_at` timestamp null, `updated_at` timestamp null) default' at line 1")
      /Users/apple/Documents/work/dev/laraveldev/genealogy/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:80

Is there any version issue

Thanks
Mohsin

**Comment by curtisdelicata** [comment]
What version of MariaDB is being used? I'll check the migrations.

**Comment by atmohsin** [comment]
Hi, 

I am using Mysql 5.6

Thanks
Mohsin

**Comment by curtisdelicata** [comment]
How did you download? Git or the tagged release?

**Comment by curtisdelicata** [comment]
I've tested a fresh migration on the latest code and not getting any errors under Vagrant or Docker.

**Comment by curtisdelicata** [comment]
What is your PHP version?

**Comment by curtisdelicata** [comment]
This may be due to using older than MySQL 5.7 / MariaDB equivalent. I'm trying to find a work around but we might not be able to support this as the code doesn't aim to work on less than PHP 7.2 either.

**Comment by atmohsin** [comment]
My PHP version is
php --version
PHP 7.1.14 (cli) (built: Feb  7 2018 18:33:30) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies

**Comment by curtisdelicata** [comment]
Are you able to upgrade your software versions? I'm building with Travis now and did get the same error on MySQL 5.6 but 5.7 is confirmed as fine (with PHP 7.2).

I'm working on build scripts and seeing if there is a workaround. It is possible manually adding nullable() to the json function will fix this.

I would like to be compatible with as much recent versions as possible.
