### ISSUE TITLE
Huge repo

### ISSUE THREAD

**Issue by hannesa2** [liberu-genealogy/genealogy-old#1827]
This repo needs a long time to check out, because it's huge.
With this command 

```
git rev-list --objects --all |
  git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' |
  sed -n 's/^blob //p' |
  sort --numeric-sort --key=2 |
  cut -c 1-12,41- |
  $(command -v gnumfmt || echo numfmt) --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest
```
I see 
<img width="431" alt="image" src="https://user-images.githubusercontent.com/3314607/147544059-e0d4c078-9e10-4c4d-821a-e63f6ab08037.png">

Is there not a smarter way to keep repo up to date without to check-in this javascript library ? (Sorry, I'm not a javascript developer)

**Comment by curtisdelicata** [comment]
You can clone with depth 1.
