### ISSUE TITLE
GEDCOM import fails on demo site

### ISSUE THREAD

**Issue by alexbelgium** [liberu-genealogy/genealogy-old#1828]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/familytree365)
* [ ] Did you check the documentation?
* [x] Did you perform a cursory search?

### Expected behavior
Gedcom uploaded, can see how great the software is.

### Actual behavior
The upload gives the message : File uploaded: conn:-tenant-
When going to the first page, an error message goes on bottom right : "Something went wrong"

**Comment by curtisdelicata** [comment]
The something went wrong error is to do with search. Gedcom should work is there any records inside people or families? Is queue listening?

**Comment by alexbelgium** [comment]
Well it allows me to select a GED file to import, says a file named "conn:-tenant-" was uploaded, but I see no tree or data. Here is a screenshot video attached - perhaps I am not doing the steps right. The ged selection appears outside of the recorded frame but I just selects the "555SAMPLE.GED" described in my initial issue. The dashboard also shows an absence of data.

I am not sure what you mean by queue listening to check if this works, but anyway the speed of upload "success" and the lack of proper name identification after upload seem to indicate that something is wrong with the upload process.

I am using the latest version of edge browser on windows 11.

https://user-images.githubusercontent.com/44178713/147688595-39e41e00-d106-4bb9-b089-9805c9423c60.mp4

?

**Comment by curtisdelicata** [comment]
Thank you for your report.

gedcom import is a job dispatched and needs artisan queue:listen or work running

**Comment by shahghasiadil** [comment]
I think gedcom import works but listening database queues makes happen to not run
