### ISSUE TITLE
Fix hard coded dna lineage command directory 

### ISSUE THREAD

**Issue by curtisdelicata** [liberu-genealogy/genealogy-old#1835]
This is  a **bug | feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/familytree365)
* [x] Did you check the documentation?
* [ ] Did you perform a cursory search?

**Comment by segunemma2003** [comment]
the bug here is that user have to install lineage 
using python3 -m pip install lineage
it has to be added to the documentation

**Comment by curtisdelicata** [comment]
the bug here means that we use a hard coded command it should use directory of current root folder
