### ISSUE TITLE
Fix Facebook google and GitHub social login

### ISSUE THREAD

**Issue by curtisdelicata** [liberu-genealogy/genealogy-old#1848]
This is  a **bug | feature request**.

### Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/familytree365)
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

**Comment by segunemma2003** [comment]
permission error causes this, the system cant write into cache( check permission for storage folder)
