### ISSUE TITLE
Smart matching between public member trees and our api / databases

### ISSUE THREAD

**Issue by curtisdelicata** [liberu-genealogy/genealogy-old#1872]
This is  a **bug | feature request**.

### Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/familytree365)
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

**Comment by curtisdelicata** [comment]
Is familytree365/api fork useful?

**Comment by segunemma2003** [comment]
K

**Comment by curtisdelicata** [comment]
Show hints or allow auto matching imports from our third party api databases to the users tenancy tree. If John Smith and Jane Doe married in same place same time and this record says doesn’t have parents but smart matching finds parents then import new ancestry data.
