### ISSUE TITLE
current docker situation

### ISSUE THREAD

**Issue by duracell** [liberu-genealogy/genealogy-old#1979]
This is  a **bug**.

### Prerequisites
* [-] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/familytree365)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
Hey, I stumbled over your project and I'm a bit confused because of the switches from the repositories and some missing information.
In the old repositories, there is an docker-compose-file and some documentation and on docker hub there are multiple different images, but all 8+ month old. I also found the "laravel-nuxt-docker" repo, but this just seems to be a forked repo from somewhere else, will there be a documentation how to integrate this repo there?

Thanks for your help

### Expected behavior
Install a docker container and like magic, everything works

### Actual behavior
no magic :'(

**Comment by curtisdelicata** [comment]
Docker is in progress. The docker files from the laravel-nuxt-docker repository will be modified to be used for genealogy and nuxt repository. It would be used with the gateway repository.
