### ISSUE TITLE
Fix gedcom import

### ISSUE THREAD

**Issue by curtisdelicata** [liberu-genealogy/genealogy-old#2038]
It isn't clear why gedcom import fails. Is it just multi tenancy broken and import actually works?

**Comment by Dip-Ghosh** [comment]
with the given description for a beginner like me, it's pretty impossible to understand where I have to change and where it is located. Kindly describe in detail

**Comment by curtisdelicata** [comment]
App/http/controllers/gedcom/store 
App/jobs/importgedcom

**Comment by curtisdelicata** [comment]
Test files, search Google for Royal92.ged
