### ISSUE TITLE
Error Creating an account

### ISSUE THREAD

**Issue by dantehemerson** [liberu-genealogy/genealogy-old#2088]
**Describe the bug**

**To Reproduce**
1. Go to 'website'
2. Click on 'register'
![image](https://user-images.githubusercontent.com/18385321/192081343-bc48d90e-8809-41be-847d-68c441a74e65.png)

**Expected behavior**
Should be able to create an account

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by curtisdelicata** [comment]
The main website needs to be updated after it was moved servers. Thank you for reporting this.

**Comment by curtisdelicata** [comment]
Fixed.
