### ISSUE TITLE
Provide clear and working instructions how to install platform.

### ISSUE THREAD

**Issue by GrzegorzDrozd** [liberu-genealogy/genealogy-old#2107]
**Describe the bug**
Hi. I would like to us this project to host a website for me and my friends. Unfortunately current installation instructions are not clear. I managed to follow them but when I enter my domain I am getting 500 error with information that tenancy not found for my domain. I managed to disable Tenancy Laravel plugin ( if it is not ready IT SHOULD not be enabled by default!) but that results in green page informing welcoming me to the project. 

**To Reproduce**
1. Go to [https://github.com/cgdprojects/genealogy](https://github.com/cgdprojects/genealogy)
2. Click on try to follow installation procedure
3. Fail.

**Expected behavior**
Successful installation. Clear information what to do next.

**Screenshots**
![image](https://user-images.githubusercontent.com/1885137/200039996-954c109c-67b6-4007-80fe-0a72dde84d96.png)

**Additional context**
Version used: 10.0.5 and master.
I commented out  App\Providers\TenancyServiceProvider::class line in config/app.php but I have no idea if this is sufficient enough.
There is no list of required php extensions (if there any beyond Laravel required extensions?).
What versions of php are supported. What database engines are supported. Is Redis required? 
What is "Broadcasting Setup" and why do I need it?
"Launch the site and log into the project with user: admin@familytree365.com, password: password" ? where? how? 

FYI: [https://github.com/cgd-ui/genealogy/issues/218](https://github.com/cgd-ui/genealogy/issues/218)

**Comment by curtisdelicata** [comment]
Tenancy has issues but is required we are trying to fix the middleware.

PHP 8.1, optional pcntl for Horizon.
MariaDB 10, Mysql 8, postgresql should also work
broadcasting is for notifications
you launch the cgd-ui install for client side
