### ISSUE TITLE
DNA Matching - show user name

### ISSUE THREAD

**Issue by curtisdelicata** [liberu-genealogy/genealogy-old#2214]
Show user name of match instead of id and link to the pending private messaging.

**Comment by robertnicjoo** [comment]
@curtisdelicata please advise of:

- file/url that user name should be shown in
- clear where "pending private messaging" is located (url)
- also where should i place link to "pending private messaging" (url)

**Comment by curtisdelicata** [comment]
Leave off private messaging for now. I've made progress, just fix dnamatching job for getting people name from users relation.
