### ISSUE TITLE
Permission Denied to Laravel Log when installing with Docker

### ISSUE THREAD

**Issue by NickRance** [liberu-genealogy/genealogy-old#232]
This is  a **bug**.

### Prerequisites
* [ x] Are you running the latest version?
* [ x] Are you reporting to the correct repository?
(This project is made of many specialized packages: https://github.com/modularsoftware)
* [ X] Did you check the documentation?
* [ X] Did you perform a cursory search?

### Description

When using the instructions from Docker.md instead of being able to view the web app you're met with a permissions error

### Steps to Reproduce
Run the "Installation Using Docker" instructions in the Docker.md file

### Expected behavior
Should have been met with the Genealogy login screen

### Actual behavior
Error screen:

UnexpectedValueException The stream or file "/application/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied

### Remedied by running the following commands:
docker-compose run --rm --no-deps genealogy-server php artisan cache:clear 
docker-compose run --rm --no-deps genealogy-server chmod -R 777 storage/
docker-compose run --rm --no-deps genealogy-server composer dump-autoload

**Comment by curtisdelicata** [comment]
Thank you for the report. It was missing from the instructions about storage permissions.

**Comment by curtisdelicata** [comment]
Added to documentation for the new branch and removed references to unused Neo4J.
