### ISSUE TITLE
Preview of App?

### ISSUE THREAD

**Issue by herpaderpaldent** [liberu-genealogy/genealogy-old#809]
Would you be able to add some screenshots? Your linked page is down and one would have no idea what you are building.

**Comment by curtisdelicata** [comment]
I will add some screenshots this week.

**Comment by herpaderpaldent** [comment]
Cheers i'd appreciate it.

**Comment by curtisdelicata** [comment]
Sorry been delays. Screenshots will be posted once I publish the first alpha of version 3.

**Comment by KarenArzumanyan** [comment]
I'm interested too ;).

**Comment by Sogl** [comment]
+1

**Comment by curtisdelicata** [comment]
I have started again with the latest Laravel Enso which uses Laravel 6. It can be seen at http://development.cgdsoftware.co.uk:8000 at the moment. Most of the features have not been ported across from our earlier version yet though.

**Comment by KarenArzumanyan** [comment]
> I have started again with the latest Laravel Enso which uses Laravel 6. It can be seen at http://development.cgdsoftware.co.uk:8000 at the moment. Most of the features have not been ported across from our earlier version yet though.

I logged in using the default login and password from Laravel Enso, and i see only admin dashboard. 
But how to see a demonstration of the functions of the geneological program?

**Comment by herpaderpaldent** [comment]
> I logged in using the default login and password from Laravel Enso, and i see only admin dashboard.
> But how to see a demonstration of the functions of the geneological program?

Same here.

**Comment by curtisdelicata** [comment]
Not much has been ported across to the latest version based on Laravel 6. I need to spend some time getting all the features working.

**Comment by herpaderpaldent** [comment]
now you got me worried. 
If i see correctly you had previously used Laravel 5.8 and porting a 5.8-> 6 is a matter of few minutes up to an hours simply because it is not a major release yet schemantic versioning. There should be not much porting involved.

**Comment by curtisdelicata** [comment]
I was not upgrading an existing version. I started with the latest Enso and was bringing features across from older version of Genealogy.

**Comment by curtisdelicata** [comment]
Preview can now be seen at https://genealogia.co.uk

**Comment by curtisdelicata** [comment]
Screenshots also available here https://www.facebook.com/modulargenealogy/posts/2625528811022494

**Comment by curtisdelicata** [comment]
We are now back to working with Enso. We plan to adapt Nuxt and all our changes and improvements done to the alternative created.
